// Angular/src/app/components/home/home.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Environment } from "../../../environments/environment";

interface FrameworkLink {
	name: string;
	url: string;
}

@Component({
	selector: 'app-home',
	standalone: true,
	imports: [CommonModule, RouterLink],
	template: `
		<div class="container mt-5 w-50">
			<h1 class="text-center">Enlaces a los Frameworks</h1>
			<ul class="list-group">
				<li *ngFor="let link of frameworks" class="list-group-item list-group-item-action list-group-item-light">
					@if (isExternalLink(link.url)) {
						<a [href]="link.url">{{ link.name }}</a>
					}
					@else if (!isExternalLink(link.url)) {
						<a [routerLink]="link.url">{{ link.name }}</a>
					}
				</li>
			</ul>
		</div>
	`,
	styles: []
})
export class HomeComponent {

	frameworks: FrameworkLink[] = [
		{ name: 'React', url: Environment.apiUrl + Environment.reactPort + '/react' },
		{ name: 'Angular', url: '/angular' },
		{ name: 'Vue', url: Environment.apiUrl + Environment.vuePort + '/vue' },
		{ name: 'Laravel', url: 'https://laravel.com' }
	];

	isExternalLink(url: string): boolean {
		return url.startsWith('http://') || url.startsWith('https://');
	}

}

// Vue/my-vue-app/src/views/Home.vue
<template>
  <div class="container mt-5 w-50">
    <h1 class="text-center">Enlaces a los Frameworks</h1>
    <ul class="list-group">
      <li v-for="link in frameworks" :key="link.name"
        class="list-group-item list-group-item-action list-group-item-light">
        <a :href="resolveLink(link.url)" v-if="isExternalLink(link.url)">{{ link.name }}</a>
        <router-link :to="link.url" v-else>{{ link.name }}</router-link>
      </li>
    </ul>
  </div>
</template>

<script>
import config from '../../config';

export default {
  name: 'HomeView',

  data() {
    return {
      frameworks: [
        { name: 'React', url: `${config.apiUrl}:${config.reactPort}/react` },
        { name: 'Angular', url: `${config.apiUrl}:${config.angularPort}/angular` },
        { name: 'Vue', url: '/vue' },
        { name: 'Laravel', url: 'https://laravel.com' }
      ]
    };
  },
  methods: {
    isExternalLink(url) {
      return url.startsWith('http://') || url.startsWith('https://');
    },
    resolveLink(url) {
      // Optional: Add any additional logic to resolve links
      return url;
    }
  }
};
</script>

<style>
/* Aquí puedes añadir estilos si es necesario */
</style>
