// Vue/src/views/EditUserForm.vue
<template>
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">Editar Usuario</h3>
      <form @submit.prevent="onSave" class="container">
        <div class="row">
          <div class="col-md-4">
            <label>Nombre:</label>
            <input type="text" class="form-control" v-model="editedUser.nombre" required />
          </div>
          <div class="col-md-4">
            <label>Apellido:</label>
            <input type="text" class="form-control" v-model="editedUser.apellido" required />
          </div>
          <div class="col-md-4">
            <label>Cédula:</label>
            <input type="text" class="form-control" v-model="editedUser.cedula" required />
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <label>Teléfono:</label>
            <input type="text" class="form-control" v-model="editedUser.telefono" required />
          </div>
          <div class="col-md-6">
            <label>Email:</label>
            <input type="email" class="form-control" v-model="editedUser.email" required />
          </div>
        </div>
        <fieldset>
          <div class="row">
            <div class="col-md-4">
              <label>Provincia:</label>
              <input type="text" class="form-control" v-model="editedUser.direccion.provincia" required />
            </div>
            <div class="col-md-4">
              <label>Cantón:</label>
              <input type="text" class="form-control" v-model="editedUser.direccion.canton" required />
            </div>
            <div class="col-md-4">
              <label>Distrito:</label>
              <input type="text" class="form-control" v-model="editedUser.direccion.distrito" required />
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <label>Barrio:</label>
              <input type="text" class="form-control" v-model="editedUser.direccion.barrio" required />
            </div>
            <div class="col-md-6">
              <label>Información Adicional:</label>
              <input type="text" class="form-control" v-model="editedUser.direccion.informacionAdicional" />
            </div>
          </div>
        </fieldset>
        <div class="row">
          <div class="col-md-6">
            <label>Tipo de Usuario:</label>
            <select class="form-control" v-model="editedUser.tipo" required>
              <option value="Normal">Normal</option>
              <option value="Administrador">Administrador</option>
            </select>
          </div>
          <div class="col-md-6">
            <label>Estado:</label>
            <select class="form-control" v-model="editedUser.estado" required>
              <option value="true">Activo</option>
              <option value="false">Inactivo</option>
            </select>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <label>Contraseña:</label>
            <input type="password" class="form-control" v-model="editedUser.password" required />
          </div>
          <div class="col-md-6">
            <label>Confirmar Contraseña:</label>
            <input type="password" class="form-control" v-model="editedUser.confirmPassword" required />
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Actualizar Usuario</button>
        <button type="button" class="btn btn-danger" @click="onCancel">Cancelar</button>
      </form>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    user: {
      type: Object,
      required: true
    }
  },
  data() {
    return {
      editedUser: {
        ...this.user
      }
    };
  },
  computed: {
    passwordMismatch() {
      return this.editedUser.password !== this.editedUser.confirmPassword;
    }
  },
  methods: {
    onSave() {
      // Aquí podrías validar y enviar el formulario editado a través de un evento
      console.log(this.editedUser);
      this.$emit('save', { ...this.editedUser });
    },
    onCancel() {
      this.$emit('cancel');
    }
  }
};
</script>

<style></style>

// Angular/src/app/components/edit-user-form/edit-user-form.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { AbstractControl, FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

import { User } from '../../models/user.model';
import { ToastrService } from 'ngx-toastr';

@Component({
	selector: 'app-edit-user-form',
	standalone: true,
	imports: [CommonModule, ReactiveFormsModule],
	templateUrl: './edit-user-form.component.html',
	styles: []
})
export class EditUserFormComponent implements OnInit {

	@Input() user: User | undefined;
	@Output() save = new EventEmitter<User>();
	@Output() cancel = new EventEmitter<void>();

	constructor (private toast: ToastrService) {}

	userForm = new FormGroup({
		id: new FormControl(0, Validators.required),
		estado: new FormControl(true, Validators.required),
		nombre: new FormControl('', Validators.required),
		apellido: new FormControl('', Validators.required),
		cedula: new FormControl('', Validators.required),
		telefono: new FormControl('', Validators.required),
		direccion: new FormGroup({
			provincia: new FormControl('', Validators.required),
			canton: new FormControl('', Validators.required),
			distrito: new FormControl('', Validators.required),
			barrio: new FormControl('', Validators.required),
			informacionAdicional: new FormControl('')
		}),
		email: new FormControl('', [Validators.required, Validators.email]),
		tipo: new FormControl('', Validators.required),
		password: new FormControl('', Validators.required),
		fechaCreacion: new FormControl(new Date(), Validators.required),
	}, { validators: this.passwordMatchValidator });

	ngOnInit(): void {
		if (this.user) {
			this.userForm.patchValue(this.user);
		}
	}

	onSave(): void {
		if (this.userForm.valid) {
			const formValue = this.userForm.value;

			if (this.user) {
				formValue.id = this.user.id;
				formValue.fechaCreacion = this.user.fechaCreacion;
			}

			const user: User = {
				id: formValue.id!,
				estado: formValue.estado!,
				nombre: formValue.nombre!,
				apellido: formValue.apellido!,
				cedula: formValue.cedula!,
				telefono: formValue.telefono!,
				direccion: {
					provincia: formValue.direccion?.provincia!,
					canton: formValue.direccion?.canton!,
					distrito: formValue.direccion?.distrito!,
					barrio: formValue.direccion?.barrio!,
					informacionAdicional: formValue.direccion?.informacionAdicional ?? ''
				},
				email: formValue.email!,
				tipo: formValue.tipo!,
				password: formValue.password!,
				fechaCreacion: formValue.fechaCreacion!
			};
			this.save.emit(user);
		}
	}

	onCancel(): void {
		this.cancel.emit();
	}

	passwordMatchValidator(control: AbstractControl): { [key: string]: boolean } | null {
		const password = control.get('password')?.value;
		const confirmPassword = control.get('confirmPassword')?.value;
		if (password !== confirmPassword) {
			return { 'mismatch': true };
		}
		return null;
	}

	// Notificaciones dentro del Componente:
	showToast(message: string, title: string, type: string): void {
		if (type === 'success') { this.toast.success(message, title); }
		if (type === 'warning') { this.toast.warning(message, title); }
		if (type === 'error') { this.toast.error(message, title); }
	}

}
<div class="card">
    <div class="card-body">
        <h3 class="card-title">Editar Usuario</h3>
        <form class='container' [formGroup]="userForm" (ngSubmit)="onSave()">
            <div class="row">
                <div class="col-md-4">
                    <label>Nombre:</label>
                    <input type="text" class="form-control" formControlName="nombre" required />
                </div>
                <div class="col-md-4">
                    <label>Apellido:</label>
                    <input type="text" class="form-control" formControlName="apellido" required />
                </div>
                <div class="col-md-4">
                    <label>Cédula:</label>
                    <input type="text" class="form-control" formControlName="cedula" required />
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label>Teléfono:</label>
                    <input type="text" class="form-control" formControlName="telefono" required />
                </div>
                <div class="col-md-6">
                    <label>Email:</label>
                    <input type="email" class="form-control" formControlName="email" type="email" required />
                </div>
            </div>
            <fieldset formGroupName="direccion">
                <div class="row" >
                    <div class="col-md-4">
                        <label>Provincia:</label>
                        <input type="text" class="form-control" formControlName="provincia" required />
                    </div>
                    <div class="col-md-4">
                        <label>Cantón:</label>
                        <input type="text" class="form-control" formControlName="canton" required />
                    </div>
                    <div class="col-md-4">
                        <label>Distrito:</label>
                        <input type="text" class="form-control" formControlName="distrito" required />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>Barrio:</label>
                        <input type="text" class="form-control" formControlName="barrio" required />
                    </div>
                    <div class="col-md-6">
                        <label>Información Adicional:</label>
                        <input type="text" class="form-control" formControlName="informacionAdicional" />
                    </div>
                </div>
            </fieldset>
            <div class="row">
                <div class="col-md-6">
                    <label>Tipo de Usuario:</label>
                    <select class="form-control" formControlName="tipo" required>
                        <option value="Normal">Normal</option>
                        <option value="Administrador">Administrador</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <label>Estado:</label>
                    <select class="form-control" formControlName="estado" required>
                        <option value="true">Activo</option>
                        <option value="false">Inactivo</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label>Contraseña:</label>
                    <input type="password" class="form-control" formControlName="password" required />
                </div>
                <div class="col-md-6">
                    <label>Confirmar Contraseña:</label>
                    <input type="password" class="form-control" formControlName="confirmPassword" required />
                    @if (userForm.hasError('mismatch') && userForm.get('confirmPassword')?.touched) {
                        {{ this.showToast('Las contraseñas no coinciden', 'Error', 'error') }}
                    }
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Actualizar Usuario</button>
            <button type="button" class="btn btn-danger" (click)="onCancel()">Cancelar</button>
        </form>
    </div>
</div>
