// Vue/src/views/UsersTable.vue
<template>
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>ID</th>
          <th>N° Cédula</th>
          <th>Nombre</th>
          <th>Teléfono</th>
          <th>Correo</th>
          <th>Tipo</th>
          <th>Estado</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="usuario in users" :key="usuario.id">
          <td>{{ usuario.id }}</td>
          <td>{{ usuario.cedula }}</td>
          <td>{{ usuario.nombre }} {{ usuario.apellido }}</td>
          <td>{{ usuario.telefono }}</td>
          <td>{{ usuario.email }}</td>
          <td>{{ usuario.tipo }}</td>
          <td>{{ usuario.estado ? 'Activo' : 'Inactivo' }}</td>
          <td>
            <button class="btn btn-info btn-sm mr-2" @click="viewUser(usuario)">
              <i class="las la-info-circle"></i>
            </button>
            <button class="btn btn-warning btn-sm mr-2" @click="editUser(usuario)">
              <i class="las la-user-edit"></i>
            </button>
            <button class="btn btn-danger btn-sm" @click="deleteUser(usuario.id)">
              <i class="las la-trash-alt"></i>
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
export default {
  props: {
    users: {
      type: Array,
      required: true,
    },
  },
  data() {
    return {
      filteredUsers: [...this.users],
    };
  },
  methods: {
    viewUser(user) {
      this.$emit('infoUser', user);
    },
    editUser(user) {
      this.$emit('editUser', user);
    },
    deleteUser(id) {
      this.$emit('deleteUser', id);
    }
  }
};
</script>

<style>

</style>

// Angular/src/app/components/users-table/users-table.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { User } from '../../models/user.model';

@Component({
	selector: 'app-users-table',
	standalone: true,
	imports: [CommonModule],
	templateUrl: './users-table.component.html',
	styleUrl: './users-table.component.css'
})
export class UsersTableComponent {

	@Input() users: User[] = [];
	@Output() editUser = new EventEmitter<User>();
	@Output() infoUser = new EventEmitter<User>();
	@Output() deleteUser = new EventEmitter<number>();

	constructor() { }

	onInfoUser(user: User): void {
		this.infoUser.emit(user);
	}

	onEditUser(user: User): void {
		this.editUser.emit(user);
	}

	onDeleteUser(userID: number | undefined): void {
		this.deleteUser.emit(userID);
	}

}
<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>N° Cédula</th>
                <th>Nombre</th>
                <th>Teléfono</th>
                <th>Correo</th>
                <th>Tipo</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let user of users">
                <td>{{ user.id }}</td>
                <td>{{ user.cedula }}</td>
                <td>{{ user.nombre }} {{ user.apellido }}</td>
                <td>{{ user.telefono }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.tipo }}</td>
                <td>{{ user.estado ? 'Activo' : 'Inactivo' }}</td>
                <td>
                    <button class="btn btn-info btn-sm mr-2" (click)="onInfoUser(user)">
                        <i class="las la-info-circle"></i>
                    </button>
                    <button class="btn btn-warning btn-sm mr-2" (click)="onEditUser(user)">
                        <i class="las la-user-edit"></i>
                    </button>
                    <button class="btn btn-danger btn-sm" (click)="onDeleteUser(user.id)">
                        <i class="las la-trash-alt"></i>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
