// Vue/src/views/AddUserForm.vue
<template>
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">Agregar Usuario</h3>
      <form @submit.prevent="onSave" class="container">
        <div class="row">
          <div class="col-md-4">
            <label>Nombre:</label>
            <input type="text" class="form-control" v-model="user.nombre" required />
          </div>
          <div class="col-md-4">
            <label>Apellido:</label>
            <input type="text" class="form-control" v-model="user.apellido" required />
          </div>
          <div class="col-md-4">
            <label>Cédula:</label>
            <input type="text" class="form-control" v-model="user.cedula" required />
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <label>Teléfono:</label>
            <input type="text" class="form-control" v-model="user.telefono" required />
          </div>
          <div class="col-md-6">
            <label>Email:</label>
            <input type="email" class="form-control" v-model="user.email" required />
          </div>
        </div>
        <fieldset>
          <div class="row">
            <div class="col-md-4">
              <label>Provincia:</label>
              <input type="text" class="form-control" v-model="user.direccion.provincia" required />
            </div>
            <div class="col-md-4">
              <label>Cantón:</label>
              <input type="text" class="form-control" v-model="user.direccion.canton" required />
            </div>
            <div class="col-md-4">
              <label>Distrito:</label>
              <input type="text" class="form-control" v-model="user.direccion.distrito" required />
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <label>Barrio:</label>
              <input type="text" class="form-control" v-model="user.direccion.barrio" required />
            </div>
            <div class="col-md-6">
              <label>Información Adicional:</label>
              <input type="text" class="form-control" v-model="user.direccion.informacionAdicional" />
            </div>
          </div>
        </fieldset>
        <div class="row">
          <div class="col-md-12">
            <label>Tipo de Usuario:</label>
            <select class="form-control" v-model="user.tipo" required>
              <option value="Normal">Normal</option>
              <option value="Administrador">Administrador</option>
            </select>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <label>Contraseña:</label>
            <input type="password" class="form-control" v-model="user.password" required />
          </div>
          <div class="col-md-6">
            <label>Confirmar Contraseña:</label>
            <input type="password" class="form-control" v-model="user.confirmPassword" required />
          </div>
        </div>
        <div class="mt-3">
          <button type="submit" class="btn btn-primary">Agregar Usuario</button>
          <button type="button" class="btn btn-danger" @click="onCancel">Cancelar</button>
        </div>
      </form>
    </div>
  </div>
</template>

<script>
export default {
  name: 'AddUserForm',
  data() {
    return {
      user: {
        nombre: '',
        apellido: '',
        cedula: '',
        telefono: '',
        email: '',
        direccion: {
          provincia: '',
          canton: '',
          distrito: '',
          barrio: '',
          informacionAdicional: ''
        },
        tipo: 'Normal',
        password: '',
        confirmPassword: ''
      },
    };
  },
  computed: {
    passwordMismatch() {
      return this.user.password !== this.user.confirmPassword;
    }
  },
  methods: {
    onSave() {
      if (this.passwordMismatch) {
        alert('Las contraseñas no coinciden');
        return;
      }
      this.$emit('save', { ...this.user });
    },
    onCancel() {
      this.$emit('cancel');
    }
  }
};
</script>

<style></style>

// Angular/src/app/components/add-user-form/add-user-form.component.ts
import { CommonModule } from '@angular/common';
import { Component, Output, EventEmitter } from '@angular/core';
import { ReactiveFormsModule, FormControl, FormGroup, Validators, AbstractControl } from '@angular/forms';

import { User } from '../../models/user.model';
import { ToastrService } from 'ngx-toastr';

@Component({
	selector: 'app-add-user-form',
	standalone: true,
	imports: [CommonModule, ReactiveFormsModule],
	templateUrl: './add-user-form.component.html',
	styles: []
})
export class AddUserFormComponent {

	@Output() save = new EventEmitter<User>();
	@Output() cancel = new EventEmitter<void>();

	constructor (private toast: ToastrService) {}

	userForm = new FormGroup({
		estado: new FormControl(true, Validators.required),
		nombre: new FormControl('', Validators.required),
		apellido: new FormControl('', Validators.required),
		cedula: new FormControl('', Validators.required),
		telefono: new FormControl('', Validators.required),
		direccion: new FormGroup({
			provincia: new FormControl('', Validators.required),
			canton: new FormControl('', Validators.required),
			distrito: new FormControl('', Validators.required),
			barrio: new FormControl('', Validators.required),
			informacionAdicional: new FormControl('')
		}),
		email: new FormControl('', [Validators.required, Validators.email]),
		tipo: new FormControl('', Validators.required),
		password: new FormControl('', Validators.required)
	}, { validators: this.passwordMatchValidator });

	onSave(): void {
		if (this.userForm.valid) {
			const formValue = this.userForm.value;
			const user: User = {
				estado: formValue.estado!,
				nombre: formValue.nombre!,
				apellido: formValue.apellido!,
				cedula: formValue.cedula!,
				telefono: formValue.telefono!,
				direccion: {
					provincia: formValue.direccion?.provincia!,
					canton: formValue.direccion?.canton!,
					distrito: formValue.direccion?.distrito!,
					barrio: formValue.direccion?.barrio!,
					informacionAdicional: formValue.direccion?.informacionAdicional ?? ''
				},
				email: formValue.email!,
				tipo: formValue.tipo!,
				password: formValue.password!
			};
			this.save.emit(user);
		}
	}

	onCancel(): void {
		this.cancel.emit();
	}

	passwordMatchValidator(control: AbstractControl): { [key: string]: boolean } | null {
		const password = control.get('password')?.value;
		const confirmPassword = control.get('confirmPassword')?.value;
		if (password !== confirmPassword) {
			return { 'mismatch': true };
		}
		return null;
	}

	// Notificaciones dentro del Componente:
	showToast(message: string, title: string, type: string): void {
		if (type === 'success') { this.toast.success(message, title); }
		if (type === 'warning') { this.toast.warning(message, title); }
		if (type === 'error') { this.toast.error(message, title); }
	}

}
<div class="card">
    <div class="card-body">
        <h3 class="card-title">Agregar Usuario</h3>
        <form class='container' [formGroup]="userForm" (ngSubmit)="onSave()">
            <div class="row">
                <div class="col-md-4">
                    <label>Nombre:</label>
                    <input type="text" class="form-control" formControlName="nombre" required />
                </div>
                <div class="col-md-4">
                    <label>Apellido:</label>
                    <input type="text" class="form-control" formControlName="apellido" required />
                </div>
                <div class="col-md-4">
                    <label>Cédula:</label>
                    <input type="text" class="form-control" formControlName="cedula" required />
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label>Teléfono:</label>
                    <input type="text" class="form-control" formControlName="telefono" required />
                </div>
                <div class="col-md-6">
                    <label>Email:</label>
                    <input type="email" class="form-control" formControlName="email" type="email" required />
                </div>
            </div>
            <fieldset formGroupName="direccion">
                <div class="row" >
                    <div class="col-md-4">
                        <label>Provincia:</label>
                        <input type="text" class="form-control" formControlName="provincia" required />
                    </div>
                    <div class="col-md-4">
                        <label>Cantón:</label>
                        <input type="text" class="form-control" formControlName="canton" required />
                    </div>
                    <div class="col-md-4">
                        <label>Distrito:</label>
                        <input type="text" class="form-control" formControlName="distrito" required />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>Barrio:</label>
                        <input type="text" class="form-control" formControlName="barrio" required />
                    </div>
                    <div class="col-md-6">
                        <label>Información Adicional:</label>
                        <input type="text" class="form-control" formControlName="informacionAdicional" />
                    </div>
                </div>
            </fieldset>
            <div class="row">
                <div class="col-md-12">
                    <label>Tipo de Usuario:</label>
                    <select class="form-control" formControlName="tipo" required>
                        <option value="Normal">Normal</option>
                        <option value="Administrador">Administrador</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label>Contraseña:</label>
                    <input type="password" class="form-control" formControlName="password" required />
                </div>
                <div class="col-md-6">
                    <label>Confirmar Contraseña:</label>
                    <input type="password" class="form-control" formControlName="confirmPassword" required />
                    @if (userForm.hasError('mismatch') && userForm.get('confirmPassword')?.touched) {
                        {{ this.showToast('Las contraseñas no coinciden', 'Error', 'error') }}
                    }
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Agregar Usuario</button>
            <button type="button" class="btn btn-danger" (click)="onCancel()">Cancelar</button>
        </form>
    </div>
</div>
